"""add client_data

Revision ID: afc0b41998a4
Revises: c62a0d495562
Create Date: 2026-06-09 10:33:27.211585
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'afc0b41998a4'
down_revision: Union[str, None] = 'c62a0d495562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_data',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=320), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_data')
    # ### end Alembic commands ###
